import curses

PRICE_FORMAT = '{:.8f}'
QTY_FORMAT = '{:.8f}'

curses.initscr()
curses.start_color()

BLACK = 0
RED = 1
GREEN = 2
YELLOW = 3
BLUE = 4
MAGENTA = 5
CYAN = 6
LIGHT_GRAY = 7
GRAY = 8
BRIGHT_RED = 9
BRIGHT_GREEN = 10
BRIGHT_YELLOW = 11
BRIGHT_BLUE = 12
BRIGHT_MAGENTA = 13
BRIGTH_CYAN = 14
BRIGHT_WHITE = 15


PRIMARY_COLORS = 1
SECONDARY_COLORS = 2
ACCENT_COLORS = 3
NEGATIVE_COLORS = 20
POSITIVE_COLORS = 30
COLUMN_COLORS = 40
ROW_COLORS = 50


curses.init_pair(PRIMARY_COLORS, BRIGHT_WHITE, BLACK)
curses.init_pair(SECONDARY_COLORS, GRAY, BLACK)
curses.init_pair(ACCENT_COLORS, BRIGHT_YELLOW, BLACK)
curses.init_pair(POSITIVE_COLORS, BRIGHT_GREEN, BLACK)
curses.init_pair(NEGATIVE_COLORS, BRIGHT_BLUE, BLACK)
curses.init_pair(COLUMN_COLORS, CYAN, BRIGHT_WHITE)
curses.init_pair(ROW_COLORS, MAGENTA, BRIGHT_WHITE)


PRIMARY_COLOR_PAIR = curses.color_pair(PRIMARY_COLORS)
SECONDARY_COLOR_PAIR = curses.color_pair(SECONDARY_COLORS)
ACCENT_COLOR_PAIR = curses.color_pair(ACCENT_COLORS)
POSITIVE_COLOR_PAIR = curses.color_pair(POSITIVE_COLORS)
NEGATIVE_COLOR_PAIR = curses.color_pair(NEGATIVE_COLORS)
COLUMN_COLOR_PAIR = curses.color_pair(COLUMN_COLORS)
ROW_COLOR_PAIR = curses.color_pair(ROW_COLORS)